services:
  - type: web
    name: mindful-moments-app
    env: python
    plan: free
    port: 5000

    build:
      - pip install --upgrade pip
      - pip install -r requirements.txt  # Install requirements FIRST (Crucial!)
      - flask db upgrade  # Run migrations AFTER requirements (Crucial!)

    startCommand: gunicorn wsgi:app
    repo: https://github.com/Freedomwithin/Mindful_Moments  # Replace with your actual repo

    envVars:
      - key: SECRET_KEY  # Only SECRET_KEY is needed here for this example.
        value: K98caJwDtWPEVjqfE50c928k6PJ4aU45 # Set a strong, random secret key in production.

    healthCheckPath: /ping
    forwardLogs: true

    autoscaling:
      minReplicas: 1
      maxReplicas: 3
      targetCPUPercentage: 75    #   - name: www.yourdomain.com