services:
  - type: web
    name: gratitude-journal
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn flask_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_APP
        value: flask_app.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///gratitude_journal.db
    healthCheckPath: /health
    autoDeploy: true

databases:
  - name: gratitude-journal-db
    databaseName: gratitude_journal
    user: gratitude_user

# Uncomment the following if you decide to use PostgreSQL instead of SQLite
# - type: postgres
#   name: gratitude-journal-db
#   ipAllowList: []
#   plan: free

# Static file hosting
staticPublishPath: ./static