services:
  - type: web
    name: mMindful_Moments_1.0
    env: python
    plan: free
    port: 5432

    build:
      - pip install -r requirements.txt
      - flask db migrate 
      - flask db upgrade

    startCommand: gunicorn wsgi:app
    repo: https://github.com/Freedomwithin/Mindful_Moments

    envVars:
      - key: SECRET_KEY
        value: uqRtbM8W3lzk3zuYJbLyyBf1zaHxkOU9u6Rupd3zsMk 
      - key: DATABASE_URL 
        value: ${DATABASE_URL}

    healthCheckPath: /ping
    forwardLogs: true

    autoscaling:
      minReplicas: 1
      maxReplicas: 3
      targetCPUPercentage: 75

databases:  # Corrected typo here
  - name: mindful-moments-db 
    plan: free
    type: postgres