services:
  - type: web
    name: gratitude-journal
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_APP
        value: flask_app.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: gratitude-journal-db
          property: connectionString
    healthCheckPath: /health
    autoDeploy: true

databases:
  - name: gratitude-journal-db
    databaseName: gratitude_journal
    user: gratitude_user
    plan: free

# Static file hosting
staticPublishPath: ./static