services:
  - type: web
    name: Mindful_Moments_1.0
    env: python
    plan: free

    # Remove the 'port' key here

    buildCommand: 
      - flask db migrate 
      - flask db upgrade

    startCommand: gunicorn wsgi:app
    repo: https://github.com/Freedomwithin/Mindful_Moments

    envVars:
      - key: SECRET_KEY
        value: uqRtbM8W3lzk3zuYJbLyyBf1zaHxkOU9u6Rupd3zsMk 
      - key: DATABASE_URL  
        value: ${DATABASE_URL}

    healthCheckPath: /ping

    # Remove 'forwardLogs' key

    # Remove 'autoscaling' key

databases:
  - name: mindful-moments-db 
    plan: free

    # Remove the 'type' key here