services:
  - type: web
    name: mMindful_Moments_1.0
    env: python
    plan: free
    port: 5432

    build:
      - pip install -r requirements.txt
      - flask db migrate 
      - flask db upgrade

    startCommand: gunicorn wsgi:app
    repo: https://github.com/Freedomwithin/Mindful_Moments

    envVars:
      - key: SECRET_KEY
        value: uqRtbM8W3lzk3zuYJbLyyBf1zaHxkOU9u6Rupd3zsMk # Replace with a *strong*, random secret key
      - key: DATABASE_URL  # This is where Render will inject the connection string
        value: postgresql://mindful_moments_user:Jht8k8bsgGrYc5wtyLV8pWVqclwqSc1b@dpg-cuue9oqn91rc73fj2e10-a/mindful_moments

    healthCheckPath: /ping
    forwardLogs: true

    autoscaling:
      minReplicas: 1
      maxReplicas: 3
      targetCPUPercentage: 75

databases:
  - name: mindful-moments-db # This name is for Render's internal use
    plan: free
    type: postgres
    # databaseName: mindful_moments # If you upgrade to a paid plan, you'll likely use these.
    # user: mindful_moments_user
    # password: YourStrongPassword # Never put a real password here in production!