services:
  - type: web
    name: mindful-moments-app
    env: python
    plan: free
    port: 5000

    build:
      - pip install -r requirements.txt
      - flask db upgrade  # Run migrations AFTER requirements

    startCommand: gunicorn wsgi:app
    repo: https://github.com/Freedomwithin/Mindful_Moments

    envVars:
      - key: SECRET_KEY
        value: Jht8k8bsgGrYc5wtyLV8pWVqclwqSc1b  # Use a strong, random secret key in production

    healthCheckPath: /ping
    forwardLogs: true

    autoscaling:
      minReplicas: 1
      maxReplicas: 3
      targetCPUPercentage: 75